server:
  port: 8083
spring:
  application:
    name: BELLING-SERVICE
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customer-db
  cloud:
    discovery:
      enabled: true
Eureka:
  instance:
    preferIpAddress: true

